apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: awo3z1f54-python 
  janus-idp.io/tekton: awo3z1f54-python
  backstage.io/kubernetes-id: awo3z1f54-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: awo3z1f54-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  