apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: awo3z1f54-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: awo3z1f54-python 
  name: awo3z1f54-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: awo3z1f54-python 
